services:
  frontend:
    build:
      context: .
      dockerfile: ./applications/webapp/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./applications/webapp/.env.local
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - seo-analysis-network

  backend:
    build:
      context: .
      dockerfile: ./applications/api/Dockerfile
    ports:
      - "5001:5000"
    env_file:
      - ./applications/api/.env
    restart: unless-stopped
    networks:
      - seo-analysis-network

networks:
  seo-analysis-network:
    driver: bridge